# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [44]:
import pandas as pa
import matplotlib as plot
file_data=pa.read_csv('./data/ccp_current_csv.csv ')
print file_data

                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St
1                  S St       NW            North Capitol St
2      Rhode Island Ave       NE            Brentwood Rd (W)
3               Mill Rd       NW                     27th St
4      Rhode Island Ave       NE            Brentwood Rd (M)
5             Mellon St       SE                      5th St
6          Nebraska Ave       NW              Northampton St
7           Military Rd       NW                     30th St
8          Nebraska Ave       NW                   Oliver St
9               16th St       NW                  Alaska Ave
10         Shoemaker St       NW                 Linnean Ave
11         Underwood St       NW             Piney Branch Rd
12             Elder St       NW                      7th St
13              26th St       NW              Northampton St
14               4th St       NW              Madison St (N)
15         Underwood Pl       NW            North Capitol St
16              20th St       NW                 Columbia Rd
17          Quintana Pl       NE                      3rd St
18         Tuckerman St       NE                  Kansas Ave
19              Eads St       NE                     45th St
20               4th St       SE                  Newcomb St
21              Belt Rd       NW                  Jenifer St
22            Oneida St       NE           New Hampshire Ave
23      Carrollsburg Pl       SW                        O St
24              23rd St       NW          Washington Cir (N)
25           Kanawha St       NW                    Utah Ave
26      Piney Branch Rd       NW                Underwood St
27              30th St       NW               Stephenson Pl
28              32nd St       NW                 Woodland Dr
29              33rd St       NW            Broad Branch Ter
..                  ...      ...                         ...
435      New Jersey Ave       NW                        F St
436             15th St       NE                     Ames Pl
437     East Capitol St       BN                        C St
438         Randolph St       NE                     25th Pl
439    South Dakota Ave       NE                Delafield St
440          Wheeler Rd       SE                 Congress St
441      New Jersey Ave       NW                        H St
442     Mount Olivet Rd       NE               Brentwood Pky
443              Oak St       NW                     16th St
444        Michigan Ave       NE                     14th St
445                C St       NE                     20th St
446        Virginia Ave       SE                  6th St (S)
447              Oak St       NW                Brown St (N)
448         Florida Ave       NE                New York Ave
449  North Carolina Ave       NE         East Capitol St (E)
450            Elder St       NW                      8th St
451          Benning Rd       SE                        G St
452           School St       SW                      4th St
453             18th St       NW                        M St
454       Longfellow St       NW                     16th St
455             10th St       NW                        M St
456          Woodley Rd       NW             Connecticut Ave
457          Woodley Rd       NW           Cathedral Ave (E)
458              3rd St       SW            Independence Ave
459             16th St       NW                 Primrose Rd
460          Woodley Rd       NW                  Woodley Pl
461         Western Ave       NW         Chevy Chase Cir (E)
462             49th St       NW                   Fulton St
463       Quackenbos St       NE           New Hampshire Ave
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu

                 TOINTERSECTION  NOOFBLOCKS                 WORKDESCRIPTION  \
0                 Longfellow St           1  Pavement Resurface/restoration
1                        3rd St           3                   Regular Cover
2              Brentwood Rd (M)           1  Pavement Resurface/restoration
3                    Cul De Sac           1  Pavement Resurface/restoration
4    14th St  Evarts St  Montan           2  Pavement Resurface/restoration
5     Martin Luther King Jr Ave           1  Pavement Resurface/restoration
6                     Oliver St           1  Pavement Resurface/restoration
7               Broad Branch Rd           4  Pavement Resurface/restoration
8                      Utah Ave           1  Pavement Resurface/restoration
9                   Primrose Rd          13                  Reconstruction
10                    Tilden St           1                       Upgrading
11              Georgia Ave (S)           1                  Reconstruction
12                       8th St           1                   Regular Cover
13               Rittenhouse St           1                   Regular Cover
14                   Peabody St           5                   Regular Cover
15                       1st St           1  Pavement Resurface/restoration
16                  Wyoming Ave           1  Pavement Resurface/restoration
17                  Eastern Ave           1  Pavement Resurface/restoration
18                  Eastern Ave           1                  Reconstruction
19                      47th St           1  Pavement Resurface/restoration
20                    Orange St           2  Pavement Resurface/restoration
21                  Military Rd           1                  Reconstruction
22                       6th St           2                   Regular Cover
23                         P St           1  Pavement Resurface/restoration
24                         M St           2  Pavement Resurface/restoration
25                      30th St           2                  Reconstruction
26                   Venable Pl           2  Pavement Resurface/restoration
27                  Tennyson St           1                   Regular Cover
28                Cleveland Ave           1                   Regular Cover
29                  Linnean Ter           1                   Regular Cover
..                          ...         ...                             ...
435                        G St           2  Pavement Resurface/restoration
436            Constitution Ave           1  Pavement Resurface/restoration
437           Anacostia Fwy (E)           2  Pavement Resurface/restoration
438                     26th St           1  Pavement Resurface/restoration
439                    Riggs Rd          10         Federal Aid Resurfacing
440                 Congress St           0             Traffic Signal Work
441                        I St           1  Pavement Resurface/restoration
442           West Virginia Ave           5  Pavement Resurface/restoration
443                Brown St (S)           1  Pavement Resurface/restoration
444                     16th St           1  Pavement Resurface/restoration
445                     22nd St           1  Pavement Resurface/restoration
446                  7th St (S)           1  Pavement Resurface/restoration
447                  Cul De Sac           1  Pavement Resurface/restoration
448                        O St           1  Pavement Resurface/restoration
449                     13th St           1  Pavement Resurface/restoration
450                 Georgia Ave           2  Pavement Resurface/restoration
451                        G St           0      High Accident Intersection
452                      6th St           1  Pavement Resurface/restoration
453  Connecticut Ave  Jefferson           1  Pavement Resurface/restoration
454                  Cul De Sac           1  Pavement Resurface/restoration
455                        N St           1  Pavement Resurface/restoration
456        29th St  Garfield St           3           Street Light Projects
457           Cathedral Ave (E)           0           Street Light Projects
458                        C St           1           Street Light Projects
459               Maryland Line           5                       Upgrading
460             Connecticut Ave           1           Street Light Projects
461                 Chestnut St          19         Federal Aid Resurfacing
462                 Garfield St           1  Pavement Resurface/restoration
463                 Eastern Ave           2  Pavement Resurface/restoration
464                 Buchanan St           1  Pavement Resurface/restoration

     YEARBUDGETED  PERCENTCOMPLETED     STATUS  MILES      ...       \
0            2004               100  Completed   0.07      ...
1            1999               100  Completed   0.33      ...
2            2004               100  Completed   0.09      ...
3            2004               100  Completed   0.07      ...
4            2005               100  Completed   0.16      ...
5            2005               100  Completed   0.20      ...
6            2004               100  Completed   0.07      ...
7            2004               100  Completed   0.35      ...
8            2005               100  Completed   0.04      ...
9            1999               100  Completed   0.97      ...
10           2004               100  Completed   0.06      ...
11           2004               100  Completed   0.08      ...
12           2004               100  Completed   0.08      ...
13           2004               100  Completed   0.16      ...
14           1999               100  Completed   0.27      ...
15           2004               100  Completed   0.14      ...
16           2004               100  Completed   0.04      ...
17           2004               100  Completed   0.12      ...
18           2004               100  Completed   0.12      ...
19           2005               100  Completed   0.16      ...
20           2005               100  Completed   0.11      ...
21           2004               100  Completed   0.16      ...
22           1999               100  Completed   0.34      ...
23           2004               100  Completed   0.06      ...
24           2004               100  Completed   0.15      ...
25           2004               100  Completed   0.21      ...
26           2004               100  Completed   0.16      ...
27           2004               100  Completed   0.15      ...
28           2004               100  Completed   0.06      ...
29           2004               100  Completed   0.14      ...
..            ...               ...        ...    ...      ...
435          2004               100  Completed   0.07      ...
436          2004               100  Completed   0.04      ...
437          2004               100  Completed   0.52      ...
438          2004               100  Completed   0.05      ...
439          2004               100  Completed   0.68      ...
440          2004               100  Completed   0.00      ...
441          2004               100  Completed   0.08      ...
442             4               100  Completed   0.33      ...
443          2005               100  Completed   0.04      ...
444          2004               100  Completed   0.11      ...
445          2004               100  Completed   0.06      ...
446          2004               100  Completed   0.16      ...
447          2004               100  Completed   0.09      ...
448          2004               100  Completed   0.05      ...
449          2004               100  Completed   0.04      ...
450          2005               100  Completed   0.11      ...
451          2004               100  Completed   0.00      ...
452          2004               100  Completed   0.13      ...
453          2005               100  Completed   0.06      ...
454          2004               100  Completed   0.10      ...
455          2005               100  Completed   0.11      ...
456          2003               100  Completed   0.27      ...
457          2003               100  Completed   0.00      ...
458          2003               100  Completed   0.10      ...
459          2005               100  Completed   0.27      ...
460          2003               100  Completed   0.07      ...
461          2004               100  Completed   1.19      ...
462          2004               100  Completed   0.12      ...
463          2005               100  Completed   0.24      ...
464          2003               100  Completed   0.02      ...

           YCOORD   LATITUDE  LONGITUDE  \
0    143205.11981  38.956747 -77.029694
1    138468.90256  38.914085 -77.012411
2    139574.10659  38.924041 -76.987221
3    138132.90198  38.911046 -77.054077
4    139657.25318  38.924790 -76.985068
5    130948.25958  38.846337 -76.998463
6    144260.95520  38.966246 -77.061675
7    143680.41824  38.961016 -77.062994
8    144332.34858  38.966889 -77.061126
9    145993.53492  38.981864 -77.036344
10   141355.75200  38.940080 -77.052639
11   144524.25789  38.968631 -77.026720
12   145484.90736  38.977286 -77.023701
13   144523.71012  38.968616 -77.055131
14   143645.75015  38.960719 -77.018034
15   144575.76052  38.969098 -77.010335
16   138911.21635  38.918061 -77.045630
17   144049.46375  38.964357 -77.001779
18   144380.43626  38.967338 -77.005814
19   136373.00889  38.895188 -76.936314
20   131031.17766  38.847084 -77.003775
21   143576.29028  38.960067 -77.080944
22   143788.68656  38.962008 -77.002159
23   133852.11487  38.872496 -77.009900
24   137368.33245  38.904161 -77.050114
25   143966.17156  38.963592 -77.058648
26   144641.00247  38.969683 -77.025542
27   144904.92557  38.972048 -77.059057
28   139907.44198  38.927027 -77.063269
29   143174.30874  38.956455 -77.065420
..            ...        ...        ...
435  136662.79676  38.897815 -77.012040
436  135988.53001  38.891741 -76.983645
437  135773.18857  38.889796 -76.963257
438  141101.24934  38.937795 -76.970647
439  142828.69431  38.953360 -76.997760
440  130311.51001  38.840601 -76.993666
441  136989.68608  38.900760 -77.013111
442  138177.81094  38.911463 -76.988473
443  140800.56074  38.935084 -77.036751
444  141629.29443  38.942555 -76.984661
445  136161.74371  38.893300 -76.975688
446  134569.68537  38.878960 -76.997601
447  140870.01258  38.935710 -77.037453
448  137873.16505  38.908719 -77.004188
449  135850.45600  38.890497 -76.988605
450  145484.83613  38.977285 -77.025480
451  134852.81001  38.881492 -76.933040
452  135121.52451  38.883930 -77.018730
453  137578.57894  38.906058 -77.041683
454  143308.79120  38.957679 -77.037145
455  137620.63091  38.906441 -77.025983
456  139776.68682  38.925854 -77.055159
457  139708.16000  38.925239 -77.050146
458  135440.84902  38.886807 -77.015201
459  146987.84913  38.990821 -77.036322
460  139730.94291  38.925443 -77.052011
461  145110.29844  38.973893 -77.068950
462  139891.73363  38.926865 -77.093990
463  143983.75188  38.963765 -77.001975
464  142147.02707  38.947219 -77.008609

                                           PROJECTNOTE  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                  POKA-2003-B-0048-JJ
4                                                  NaN
5                                                  NaN
6                                                  NaN
7                                                  NaN
8                                                  NaN
9    Reconstruction of 16th St. from Alaska to Prim...
10                                                 NaN
11                                                 NaN
12                                                 NaN
13                                                 NaN
14                                                 NaN
15                                                 NaN
16                                 POKA-2003-B-0048-JJ
17                                                 NaN
18                                                 NaN
19                                                 NaN
20                                                 NaN
21                                                 NaN
22                                                 NaN
23                                                 NaN
24                                                 NaN
25                                                 NaN
26                                                 NaN
27                                                 NaN
28                                                 NaN
29                                                 NaN
..                                                 ...
435                                                NaN
436                                                NaN
437                                FY-04 per Sylvester
438                                                NaN
439    Per Berehager  construction will begin in FY-04
440                                                NaN
441                                                NaN
442                                                NaN
443                                POKA-2003-B-0048-JJ
444                                                NaN
445                                                NaN
446                                                NaN
447                                POKA-2003-B-0048-JJ
448                                                NaN
449                                                NaN
450                                                NaN
451                                                NaN
452                                POKA-2003-B-0048-JJ
453                                POKA-2004-B-0016-JJ
454                                                NaN
455                                                NaN
456                                                NaN
457                                                NaN
458                                                NaN
459                                                NaN
460                                                NaN
461                                                NaN
462                                   2nd Aid to State
463                                                NaN
464                                                NaN

                                           PROJECTNAME         PROJECTMGR  \
0                                               FedAid    Paul Stephenson
1                                                  NaN                NaN
2             Fedral Aid Citywide Pavement Restoration  Mohamed Abdullahi
3    Citywide Pavement Restoration Contract (Local ...    Maduabuchi Udeh
4                                                  NaN                NaN
5                                        CIP_2004-2009              FY-05
6                        Citywide Pavement Restoration    Paul Stephenson
7                                       FedAid_6YR_CIP    Paul Stephenson
8                         Citywide Pavement Restoratin    paul Stephenson
9    Recons of 16TH St. from Alaska to Prime Rose  ...   Eskender  Konjit
10                                                 NaN                NaN
11                       Citywide Pavement Restoration    Paul Stephenson
12                                                 NaN                NaN
13                                                 NaN                NaN
14                                                 NaN                NaN
15                       Citywidy Pavement Restoration    Paul Stephenson
16   Citywide Pavement Restoration Contract (Local ...    Maduabuchi Udeh
17                       Citywide Pavement Restoration    Paul Stephenson
18                       Citywide Pavement Restoration    Paul Stephenson
19   CITYWIDE PAVEMENT RESTORATION CONTRACT (LOCAL ...                NaN
20   CITYWIDE PAVEMENT RESTORATION CONTRACT (LOCAL ...                NaN

### 3.1.a  what is its shape and what does that mean?

In [8]:
file_data.size

12555

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [9]:
file_data['QUADRANT'].value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b

In [21]:
import numpy as np
from numpy import array
a = array( [9,8,7,6] )
b = array([4,5,6,7])
print a+b #operational use
np.add(a,b) ## Using add function

[13 13 13 13]

array([13, 13, 13, 13])

### 3.3.2 subtraction a-b

In [22]:
print a-b ## using '-' operator
np.subtract(a,b) ## using subtract function

[ 5  3  1 -1]

array([ 5,  3,  1, -1])

### 3.3.3 multiplication a*b

In [23]:
print a*b ## using '*' operator
np.multiply(a,b) ## using multiply function

[36 40 42 42]

array([36, 40, 42, 42])

### 3.3.4 divsion a/b

In [24]:
print a/b ## using '/' operator
np.divide(a,b) ## using divide function

[2 1 1 0]

array([2, 1, 1, 0])

### 3.3.5 modulo  a%b

In [25]:
print a%b ## using '%' operator
np.mod(a,b) ## using mod function

[1 3 1 6]

array([1, 3, 1, 6])

### 3.3.6 power  a^b

In [26]:
print a**b ## using '**' operator
np.power(a,b) ## using power function

[  6561  32768 117649 279936]

array([  6561,  32768, 117649, 279936])

## Homework 3.4
Find your own data and load it into a dataframe

I found this dataset interesting because Game of Thrones is one of the hit fantacy show in the television. The dataset contains the collection of all battles in the series.

In [60]:
import pandas as pa
data_frame=pa.read_csv('./data/battles.csv')
data_frame

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN
5,Battle of the Camps,298,6,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,0.0,0.0,6000.0,12625.0,"Robb Stark, Tytos Blackwood, Brynden Tully","Lord Andros Brax, Forley Prester",1.0,Riverrun,The Riverlands,NaN
6,Sack of Darry,298,7,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Darry,...,0.0,0.0,NaN,NaN,Gregor Clegane,Lyman Darry,1.0,Darry,The Riverlands,NaN
7,Battle of Moat Cailin,299,8,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,NaN,NaN,Victarion Greyjoy,NaN,1.0,Moat Cailin,The North,NaN
8,Battle of Deepwood Motte,299,9,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,1000.0,NaN,Asha Greyjoy,NaN,1.0,Deepwood Motte,The North,NaN
9,Battle of the Stony Shore,299,10,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,0.0,264.0,NaN,Theon Greyjoy,NaN,1.0,Stony Shore,The North,Greyjoy's troop number based on the Battle of ...
10,Battle of Torrhen's Square,299,11,Robb Stark,Balon/Euron Greyjoy,Stark,NaN,NaN,NaN,Greyjoy,...,0.0,0.0,244.0,900.0,"Rodrik Cassel, Cley Cerwyn",Dagmer Cleftjaw,1.0,Torrhen's Square,The North,Greyjoy's troop number comes from the 264 esti...
11,Battle of Winterfell,299,12,Balon/Euron Greyjoy,Robb Stark,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,1.0,20.0,NaN,Theon Greyjoy,Bran Stark,1.0,Winterfell,The North,It isn't mentioned how many Stark men are left...
12,Sack of Torrhen's Square,299,13,Balon/Euron Greyjoy,Balon/Euron Greyjoy,Greyjoy,NaN,NaN,NaN,Stark,...,0.0,1.0,NaN,NaN,Dagmer Cleftjaw,NaN,1.0,Torrhen's Square,The North,NaN
13,Sack of Winterfell,299,14,Joffrey/Tommen Baratheon,Robb Stark,Bolton,Greyjoy,NaN,NaN,Stark,...,1.0,0.0,618.0,2000.0,"Ramsay Snow, Theon Greyjoy","Rodrik Cassel, Cley Cerwyn, Leobald Tallhart",1.0,Winterfell,The North,Since House Bolton betrays the Starks for Hous...
14,Battle of Oxcross,299,15,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,6000.0,10000.0,"Robb Stark, Brynden Tully","Stafford Lannister, Roland Crakehall, Antario ...",1.0,Oxcross,The Westerlands,NaN
15,Siege of Storm's End,299,16,Stannis Baratheon,Renly Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,1.0,0.0,5000.0,20000.0,"Stannis Baratheon, Davos Seaworth","Renly Baratheon, Cortnay Penrose, Loras Tyrell...",1.0,Storm's End,The Stormlands,NaN
16,Battle of the Fords,299,17,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,0.0,20000.0,10000.0,"Tywin Lannister, Flement Brax, Gregor Clegane,...","Edmure Tully, Jason Mallister, Karyl Vance",1.0,Red Fork,The Riverlands,NaN
17,Sack of Harrenhal,299,18,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,0.0,100.0,100.0,"Roose Bolton, Vargo Hoat, Robett Glover",Amory Lorch,1.0,Harrenhal,The Riverlands,NaN
18,Battle of the Crag,299,19,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,0.0,0.0,6000.0,NaN,"Robb Stark, Smalljon Umber, Black Walder Frey",Rolph Spicer,1.0,Crag,The Westerlands,NaN
19,Battle of the Blackwater,299,20,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,NaN,NaN,NaN,Lannister,...,1.0,1.0,21000.0,7250.0,"Stannis Baratheon, Imry Florent, Guyard Morrig...","Tyrion Lannister, Jacelyn Bywater, Sandor Cleg...",1.0,King's Landing,The Crownlands,NaN
20,Siege of Darry,299,21,Robb Stark,Joffrey/Tommen Baratheon,Darry,NaN,NaN,NaN,Lannister,...,0.0,0.0,NaN,NaN,Helman Tallhart,NaN,1.0,Darry,The Riverlands,NaN
21,Battle of Duskendale,299,22,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,0.0,3000.0,NaN,"Robertt Glover, Helman Tallhart","Randyll Tarly, Gregor Clegane",1.0,Duskendale,The Crownlands,NaN
22,Battle of the Burning Septry,299,23,NaN,NaN,Brotherhood without Banners,NaN,NaN,NaN,Brave Companions,...,0.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,The Riverlands,NaN
23,Battle of the Ruby Ford,299,24,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Stark,...,0.0,0.0,NaN,6000.0,Gregor Clegane,"Roose Bolton, Wylis Manderly",NaN,Ruby Ford,The Riverlands,NaN
24,Retaking of Harrenhal,299,25,Joffrey/Tommen Baratheon,NaN,Lannister,NaN,NaN,NaN,Brave Companions,...,1.0,0.0,NaN,NaN,Gregor Clegane,Vargo Hoat,1.0,Harrenhal,The Riverlands,NaN
25,The Red Wedding,299,26,Joffrey/Tommen Baratheon,Robb Stark,Frey,Bolton,NaN,NaN,Stark,...,1.0,1.0,3500.0,3500.0,"Walder Frey, Roose Bolton, Walder Rivers",Robb Stark,1.0,The Twins,The Riverlands,This observation refers to the battle against ...
26,Siege of Seagard,299,27,Robb Stark,Joffrey/Tommen Baratheon,Frey,NaN,NaN,NaN,Mallister,...,0.0,1.0,NaN,NaN,Walder Frey,Jason Mallister,1.0,Seagard,The Riverlands,NaN
27,Battle of Castle Black,300,28,Stannis Baratheon,Mance Rayder,Free folk,Thenns,Giants,NaN,Night's Watch,...,1.0,1.0,100000.0,1240.0,"Mance Rayder, Tormund Giantsbane, Harma Dogshe...","Stannis Baratheon, Jon Snow, Donal Noye, Cotte...",0.0,Castle Black,Beyond the Wall,NaN
28,Fall of Moat Cailin,300,29,Joffrey/Tommen Baratheon,Balon/Euron Greyjoy,Bolton,NaN,NaN,NaN,Greyjoy,...,0.0,0.0,NaN,NaN,Ramsey Bolton,NaN,0.0,Moat Cailin,The North,NaN
29,Sack of Saltpans,300,30,NaN,NaN,Brave Companions,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,Rorge,NaN,0.0,Saltpans,The Riverlands,NaN
30,Retaking of Deepwood Motte,300,31,Stannis Baratheon,Balon/Euron Greyjoy,Baratheon,Karstark,Mormont,Glover,Greyjoy,...,0.0,0.0,4500.0,200.0,"Stannis Baratheon, Alysane Mormot",Asha Greyjoy,0.0,Deepwood Motte,The North,NaN
31,Battle of the Shield Islands,300,32,Balon/Euron Greyjoy,Joffrey/Tommen Baratheon,Greyjoy,NaN,NaN,NaN,Tyrell,...,0.0,0.0,NaN,NaN,"Euron Greyjoy, Victarion Greyjoy",NaN,0.0,Shield Islands,The Reach,NaN
32,"Invasion of Ryamsport, Vinetown, and Starfish ...",300,33,Balon/Euron Greyjoy,Joffrey/Tommen Baratheon,Greyjoy,NaN,NaN,NaN,Tyrell,...,0.0,0.0,NaN,NaN,"Euron Greyjoy, Victarion Greyjoy",NaN,0.0,"Ryamsport, Vinetown, Starfish Harbor",The Reach,NaN
33,Second Seige of Storm's End,300,34,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,NaN,200.0,"Mace Tyrell, Mathis Rowan",Gilbert Farring,0.0,Storm's End,The Stormlands,NaN
34,Siege of Dragonstone,300,35,Joffrey/Tommen Baratheon,Stannis Baratheon,Baratheon,NaN,NaN,NaN,Baratheon,...,0.0,0.0,2000.0,NaN,"Loras Tyrell, Raxter Redwyne",Rolland Storm,0.0,Dragonstone,The Stormlands,NaN
35,Siege of Riverrun,300,36,Joffrey/Tommen Baratheon,Robb Stark,Lannister,Frey,NaN,NaN,Tully,...,0.0,0.0,3000.0,NaN,"Daven Lannister, Ryman Fey, Jaime Lannister",Brynden Tully,0.0,Riverrun,The Riverlands,NaN
36,Siege of Raventree,300,37,Joffrey/Tommen Baratheon,Robb Stark,Bracken,Lannister,NaN,NaN,Blackwood,...,0.0,1.0,1500.0,NaN,"Jonos Bracken, Jaime Lannister",Tytos Blackwood,0.0,Raventree,The Riverlands,NaN
37,Siege of Winterfell,300,38,Stannis Baratheon,Joffrey/Tommen Baratheon,Baratheon,Karstark,Mormont,Glover,Bolton,...,NaN,NaN,5000.0,8000.0,Stannis Baratheon,Roose Bolton,0.0,Winterfell,The North,NaN

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [61]:
data_frame.shape ## To know the number of rows and columns

(38, 25)

In [62]:
data_frame.size

950

In [63]:
data_frame.columns ## Provides the columns present in the data frame

Index([u'name', u'year', u'battle_number', u'attacker_king', u'defender_king',
       u'attacker_1', u'attacker_2', u'attacker_3', u'attacker_4',
       u'defender_1', u'defender_2', u'defender_3', u'defender_4',
       u'attacker_outcome', u'battle_type', u'major_death', u'major_capture',
       u'attacker_size', u'defender_size', u'attacker_commander',
       u'defender_commander', u'summer', u'location', u'region', u'note'],
      dtype='object')

In [64]:
data_frame.describe() ## .describe() method provides the statistics of the battle.

,year,battle_number,defender_3,defender_4,major_death,major_capture,attacker_size,defender_size,summer
count,38.000000,38.000000,0.0,0.0,37.000000,37.000000,24.000000,19.000000,37.000000
mean,299.105263,19.500000,NaN,NaN,0.351351,0.297297,9942.541667,6428.157895,0.702703
std,0.689280,11.113055,NaN,NaN,0.483978,0.463373,20283.092065,6225.182106,0.463373
min,298.000000,1.000000,NaN,NaN,0.000000,0.000000,20.000000,100.000000,0.000000
25%,299.000000,10.250000,NaN,NaN,0.000000,0.000000,1375.000000,1070.000000,0.000000
50%,299.000000,19.500000,NaN,NaN,0.000000,0.000000,4000.000000,6000.000000,1.000000
75%,300.000000,28.750000,NaN,NaN,1.000000,1.000000,8250.000000,10000.000000,1.000000
max,300.000000,38.000000,NaN,NaN,1.000000,1.000000,100000.000000,20000.000000,1.000000

In [65]:
## Checking for the team size of attackers and defenders.  

if data_frame['attacker_size'].max() > data_frame['attacker_size'].max():
    print "Strong attacker team"
else:
    print "Strong defender team"

Strong defender team

In [66]:
data_frame[['name','attacker_king','defender_king','attacker_outcome','location']][:20] ## Retrieving the first 20 rows of the desired columns

,name,attacker_king,defender_king,attacker_outcome,location
0,Battle of the Golden Tooth,Joffrey/Tommen Baratheon,Robb Stark,win,Golden Tooth
1,Battle at the Mummer's Ford,Joffrey/Tommen Baratheon,Robb Stark,win,Mummer's Ford
2,Battle of Riverrun,Joffrey/Tommen Baratheon,Robb Stark,win,Riverrun
3,Battle of the Green Fork,Robb Stark,Joffrey/Tommen Baratheon,loss,Green Fork
4,Battle of the Whispering Wood,Robb Stark,Joffrey/Tommen Baratheon,win,Whispering Wood
5,Battle of the Camps,Robb Stark,Joffrey/Tommen Baratheon,win,Riverrun
6,Sack of Darry,Joffrey/Tommen Baratheon,Robb Stark,win,Darry
7,Battle of Moat Cailin,Balon/Euron Greyjoy,Robb Stark,win,Moat Cailin
8,Battle of Deepwood Motte,Balon/Euron Greyjoy,Robb Stark,win,Deepwood Motte
9,Battle of the Stony Shore,Balon/Euron Greyjoy,Robb Stark,win,Stony Shore
10,Battle of Torrhen's Square,Robb Stark,Balon/Euron Greyjoy,win,Torrhen's Square
11,Battle of Winterfell,Balon/Euron Greyjoy,Robb Stark,win,Winterfell
12,Sack of Torrhen's Square,Balon/Euron Greyjoy,Balon/Euron Greyjoy,win,Torrhen's Square
13,Sack of Winterfell,Joffrey/Tommen Baratheon,Robb Stark,win,Winterfell
14,Battle of Oxcross,Robb Stark,Joffrey/Tommen Baratheon,win,Oxcross
15,Siege of Storm's End,Stannis Baratheon,Renly Baratheon,win,Storm's End
16,Battle of the Fords,Joffrey/Tommen Baratheon,Robb Stark,loss,Red Fork
17,Sack of Harrenhal,Robb Stark,Joffrey/Tommen Baratheon,win,Harrenhal
18,Battle of the Crag,Robb Stark,Joffrey/Tommen Baratheon,win,Crag
19,Battle of the Blackwater,Stannis Baratheon,Joffrey/Tommen Baratheon,loss,King's Landing

In [12]:
data_frame['attacker_outcome'].value_counts()  ## Total number of wins/losses in the battles

win     32
loss     5
Name: attacker_outcome, dtype: int64

In [28]:
data_frame[['attacker_king','defender_king','attacker_outcome']] ## Retrieving attacker_king,defender_king and attacker_outcome columns

               attacker_king             defender_king attacker_outcome
0   Joffrey/Tommen Baratheon                Robb Stark              win
1   Joffrey/Tommen Baratheon                Robb Stark              win
2   Joffrey/Tommen Baratheon                Robb Stark              win
3                 Robb Stark  Joffrey/Tommen Baratheon             loss
4                 Robb Stark  Joffrey/Tommen Baratheon              win
5                 Robb Stark  Joffrey/Tommen Baratheon              win
6   Joffrey/Tommen Baratheon                Robb Stark              win
7        Balon/Euron Greyjoy                Robb Stark              win
8        Balon/Euron Greyjoy                Robb Stark              win
9        Balon/Euron Greyjoy                Robb Stark              win
10                Robb Stark       Balon/Euron Greyjoy              win
11       Balon/Euron Greyjoy                Robb Stark              win
12       Balon/Euron Greyjoy       Balon/Euron Greyjoy              win
13  Joffrey/Tommen Baratheon                Robb Stark              win
14                Robb Stark  Joffrey/Tommen Baratheon              win
15         Stannis Baratheon           Renly Baratheon              win
16  Joffrey/Tommen Baratheon                Robb Stark             loss
17                Robb Stark  Joffrey/Tommen Baratheon              win
18                Robb Stark  Joffrey/Tommen Baratheon              win
19         Stannis Baratheon  Joffrey/Tommen Baratheon             loss
20                Robb Stark  Joffrey/Tommen Baratheon              win
21                Robb Stark  Joffrey/Tommen Baratheon             loss
22                       NaN                       NaN              win
23  Joffrey/Tommen Baratheon                Robb Stark              win
24  Joffrey/Tommen Baratheon                       NaN              win
25  Joffrey/Tommen Baratheon                Robb Stark              win
26                Robb Stark  Joffrey/Tommen Baratheon              win
27         Stannis Baratheon              Mance Rayder             loss
28  Joffrey/Tommen Baratheon       Balon/Euron Greyjoy              win
29                       NaN                       NaN              win
30         Stannis Baratheon       Balon/Euron Greyjoy              win
31       Balon/Euron Greyjoy  Joffrey/Tommen Baratheon              win
32       Balon/Euron Greyjoy  Joffrey/Tommen Baratheon              win
33  Joffrey/Tommen Baratheon         Stannis Baratheon              win
34  Joffrey/Tommen Baratheon         Stannis Baratheon              win
35  Joffrey/Tommen Baratheon                Robb Stark              win
36  Joffrey/Tommen Baratheon                Robb Stark              win
37         Stannis Baratheon  Joffrey/Tommen Baratheon              NaN

In [27]:
max_wins = data_frame[data_frame['attacker_outcome'] == "win"] ## Counts the total number of wins by each attacker
max_wins['attacker_king'].value_counts()

Joffrey/Tommen Baratheon    13
Robb Stark                   8
Balon/Euron Greyjoy          7
Stannis Baratheon            2
Name: attacker_king, dtype: int64

In [70]:

max_wins['attacker_king'].value_counts().plot()

In [46]:
## sum of major deaths and major captures occured in each region

data = data_frame.groupby("region").sum()[["major_death", "major_capture"]]
print data

                 major_death  major_capture
region
Beyond the Wall          1.0            1.0
The Crownlands           2.0            1.0
The North                1.0            2.0
The Reach                0.0            0.0
The Riverlands           6.0            6.0
The Stormlands           1.0            0.0
The Westerlands          2.0            1.0